language: python
python:
- '3.6'
install:
- pip install --no-cache-dir --process-dependency-links .
- pip install codecov coverage requests_mock nose_parameterized
script: nosetests --with-coverage --cover-package=tooldog
after_success: codecov
deploy:
  provider: pypi
  user: khillion
  password:
    secure: wXjAUwTd1KljIsnMo3sqOhX3pFuaHE6EbN0mN69cr6iK33XantV1Sgq0onylak6NYpOCih4ivpos5lzM/onhHpH/T4MIoACwUzXWaQctKmkozS4JU6m3d729mxHBbxpzp2H50V56cO7Bm+ydsbx9lgzcygiAo7rG316SezbEEOTw4FZHDOJ0P5MPhTLj2NMNS77iBSViuLxwjxBH32eXIz874fJ9HUpf1uoPW8XDsAGcn9GsZ6D7nSRS3IUD9S10Gu5t9+38+69Ee5WwbUx4Zz05Xv2mzDvAquY4zUXbSuDGxpFFMeiO2Z1NA4l+52ZXFgGWTboB+emxJF+6FYQ/yMoJ6qv6tVA5xA5rWDx260Eyyhg/hjGjkBryZ92/D7EHdUlSkiXZb3odvtkb4C5dB/wV+SU4vBorZuLn1AVx9errPuNym407lf0pdnl8KSXzkvhzG1DFX6qWemC255gwCylxmZdE/MT1E2NdWpwlIFGxvQu5gfbBa8CVI0/NWG0RN0oKbrRSxHxk5B5k2Oxv58Dxr3kvA/9KcqyMwuurAXKWwVVGYevHCoxZDefakwH1CLOSlfJFTGyFbal/ZvsL4qhJmTsEDbm1pcGOAxgcFTyJ+hZB3rzhJb6siF5YQ4gtMh553/Ice4CsXYRodIqpIaS5Ri8zjV34ncdAJJHKjoI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: bio-tools/tooldog
